# Generated by Django 5.1.4 on 2025-05-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('agriculture', 'Agriculture & Agro-processing'), ('banking', 'Banking & Finance'), ('construction', 'Construction & Real Estate'), ('education', 'Education & Training'), ('health', 'Healthcare & Pharmaceuticals'), ('hospitality', 'Hospitality & Tourism'), ('manufacturing', 'Manufacturing'), ('mining', 'Mining & Natural Resources'), ('retail', 'Retail & E-commerce'), ('technology', 'Technology & IT Services'), ('telecom', 'Telecommunications'), ('transport', 'Transportation & Logistics'), ('utilities', 'Utilities & Energy'), ('other', 'Other Services')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('product_category', models.CharField(blank=True, choices=[('airtime', 'Airtime - Internet'), ('association', 'Association and Organization'), ('church', 'Church'), ('bank', 'Bank Integration'), ('goods', 'Goods and Services'), ('healthcare', 'Healthcare'), ('insurance', 'Insurance'), ('investments', 'Investments'), ('schoolfees', 'School Fees'), ('utility', 'Utility')], max_length=50, null=True, verbose_name='What category does your product or service belong to?')),
                ('phone_number', models.CharField(max_length=20)),
                ('sales_rep', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sales Rep Who Referred Kemy to You?')),
                ('physical_address', models.TextField(blank=True, null=True, verbose_name='Physical address')),
                ('monthly_transaction_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='How much would you say you transact monthly?')),
            ],
        ),
    ]
