# Generated by Django 5.1.4 on 2025-05-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='account_number',
            field=models.BooleanField(default=False, verbose_name='Do your customers require an account number / identified to make payment or can anyone pay?'),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='director_id',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='is_disbursment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='is_entity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='max_payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Maximum payment amount'),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='min_payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Minimum payment amount'),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='mobile_money_network',
            field=models.CharField(blank=True, choices=[('mobile_mony', 'Mobile Money'), ('bank', 'Bank')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='operation',
            field=models.BooleanField(default=False, verbose_name='Do you operate a business that requires your customers to pay for packages?'),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='service_charge',
            field=models.CharField(blank=True, choices=[('split', 'Split - 1% customer, 0.5% Business'), ('business', 'Business - 1.5%'), ('customer', 'Customer - 1.5%')], max_length=50, null=True, verbose_name='Who bears the service charge?'),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='settlement_method',
            field=models.CharField(blank=True, choices=[('days', 'After two days'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50, null=True, verbose_name='How frequenty do you want to be settled?'),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='settlement_money',
            field=models.CharField(blank=True, choices=[('mobile_mony', 'Mobile Money'), ('bank', 'Bank')], max_length=50, null=True, verbose_name='Where should you settle money to be sent to?'),
        ),
    ]
