# Generated by Django 5.1.4 on 2025-05-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_businessuser_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='mobile_money_network',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('telecel', 'Telecel Cash'), ('airteltigo', 'AirtelTigo Money')], max_length=50, null=True),
        ),
    ]
