# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/invoice/payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'v1/invoice/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v1.invoice import common_pb2 as v1_dot_invoice_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18v1/invoice/payment.proto\x12\ninvoice.v1\x1a\x17v1/invoice/common.proto\"\xcb\x01\n\x0ePaymentRequest\x12\x16\n\x0einvoice_number\x18\x01 \x01(\t\x12\x13\n\x0bmerchant_id\x18\x02 \x01(\x05\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\x12&\n\x08provider\x18\x04 \x01(\x0e\x32\x14.invoice.v1.Provider\x12\x12\n\naccount_no\x18\x05 \x01(\t\x12!\n\x06\x61mount\x18\x06 \x01(\x0b\x32\x11.invoice.v1.Money\x12\x15\n\rcustomer_name\x18\x07 \x01(\t\"\xa5\x01\n\x0fPaymentResponse\x12\x16\n\x0einvoice_number\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\x12)\n\x06status\x18\x04 \x01(\x0e\x32\x19.invoice.v1.PaymentStatus\x12\x14\n\x0c\x65xternal_ref\x18\x05 \x01(\t\x12!\n\x06\x61mount\x18\x06 \x01(\x0b\x32\x11.invoice.v1.MoneyB\x0cZ\ngo/invoiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.invoice.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\ngo/invoice'
  _globals['_PAYMENTREQUEST']._serialized_start=66
  _globals['_PAYMENTREQUEST']._serialized_end=269
  _globals['_PAYMENTRESPONSE']._serialized_start=272
  _globals['_PAYMENTRESPONSE']._serialized_end=437
# @@protoc_insertion_point(module_scope)
