# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kemy/invoice/payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kemy/invoice/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kemy.invoice import common_pb2 as kemy_dot_invoice_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1akemy/invoice/payment.proto\x12\x0ckemy.invoice\x1a\x19kemy/invoice/common.proto\"\xcf\x01\n\x0ePaymentRequest\x12\x16\n\x0einvoice_number\x18\x01 \x01(\t\x12\x13\n\x0bmerchant_id\x18\x02 \x01(\x05\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\x12(\n\x08provider\x18\x04 \x01(\x0e\x32\x16.kemy.invoice.Provider\x12\x12\n\naccount_no\x18\x05 \x01(\t\x12#\n\x06\x61mount\x18\x06 \x01(\x0b\x32\x13.kemy.invoice.Money\x12\x15\n\rcustomer_name\x18\x07 \x01(\t\"\xa9\x01\n\x0fPaymentResponse\x12\x16\n\x0einvoice_number\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\x12+\n\x06status\x18\x04 \x01(\x0e\x32\x1b.kemy.invoice.PaymentStatus\x12\x14\n\x0c\x65xternal_ref\x18\x05 \x01(\t\x12#\n\x06\x61mount\x18\x06 \x01(\x0b\x32\x13.kemy.invoice.MoneyB2Z0gitlab.com/rippletech/protos/gen/go/kemy/invoiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kemy.invoice.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0gitlab.com/rippletech/protos/gen/go/kemy/invoice'
  _globals['_PAYMENTREQUEST']._serialized_start=72
  _globals['_PAYMENTREQUEST']._serialized_end=279
  _globals['_PAYMENTRESPONSE']._serialized_start=282
  _globals['_PAYMENTRESPONSE']._serialized_end=451
# @@protoc_insertion_point(module_scope)
