# Generated by Django 5.1.4 on 2025-05-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kemyweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Last name'),
        ),
    ]
