# Generated by Django 5.1.4 on 2025-05-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kemyweb', '0002_alter_businessinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name'),
        ),
    ]
