# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1.payment import common_pb2 as v1_dot_payment_dot_common__pb2
from v1.payment import payment_pb2 as v1_dot_payment_dot_payment__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in v1/payment/payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterProvider = channel.unary_unary(
                '/payment.v1.PaymentService/RegisterProvider',
                request_serializer=v1_dot_payment_dot_payment__pb2.RegisterProviderRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_common__pb2.Provider.FromString,
                _registered_method=True)
        self.GetProvider = channel.unary_unary(
                '/payment.v1.PaymentService/GetProvider',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetProviderRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_common__pb2.Provider.FromString,
                _registered_method=True)
        self.ListProviders = channel.unary_unary(
                '/payment.v1.PaymentService/ListProviders',
                request_serializer=v1_dot_payment_dot_payment__pb2.ListProvidersRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.ListProvidersResponse.FromString,
                _registered_method=True)
        self.UpdateProvider = channel.unary_unary(
                '/payment.v1.PaymentService/UpdateProvider',
                request_serializer=v1_dot_payment_dot_payment__pb2.UpdateProviderRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateProviderStatus = channel.unary_unary(
                '/payment.v1.PaymentService/UpdateProviderStatus',
                request_serializer=v1_dot_payment_dot_payment__pb2.UpdateProviderStatusRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.OnboardMerchant = channel.unary_unary(
                '/payment.v1.PaymentService/OnboardMerchant',
                request_serializer=v1_dot_payment_dot_common__pb2.MerchantAccount.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateMerchant = channel.unary_unary(
                '/payment.v1.PaymentService/UpdateMerchant',
                request_serializer=v1_dot_payment_dot_common__pb2.MerchantAccount.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetMerchantActiveStatus = channel.unary_unary(
                '/payment.v1.PaymentService/SetMerchantActiveStatus',
                request_serializer=v1_dot_payment_dot_payment__pb2.SetMerchantActiveStatusRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AddProviderAccountToMerchant = channel.unary_unary(
                '/payment.v1.PaymentService/AddProviderAccountToMerchant',
                request_serializer=v1_dot_payment_dot_common__pb2.MerchantProviderAccount.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateMerchantProviderAccount = channel.unary_unary(
                '/payment.v1.PaymentService/UpdateMerchantProviderAccount',
                request_serializer=v1_dot_payment_dot_common__pb2.MerchantProviderAccount.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveProviderAccountFromMerchant = channel.unary_unary(
                '/payment.v1.PaymentService/RemoveProviderAccountFromMerchant',
                request_serializer=v1_dot_payment_dot_payment__pb2.RemoveProviderAccountRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMerchantProviderAccounts = channel.unary_unary(
                '/payment.v1.PaymentService/GetMerchantProviderAccounts',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetMerchantProviderAccountsRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.GetMerchantProviderAccountsResponse.FromString,
                _registered_method=True)
        self.GetMerchantAccounts = channel.unary_unary(
                '/payment.v1.PaymentService/GetMerchantAccounts',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetMerchantAccountsRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.GetMerchantAccountsResponse.FromString,
                _registered_method=True)
        self.GetInvoiceForPayment = channel.unary_unary(
                '/payment.v1.PaymentService/GetInvoiceForPayment',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetInvoiceForPaymentRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_common__pb2.MerchantInvoicePaymentDetails.FromString,
                _registered_method=True)
        self.GetTransaction = channel.unary_unary(
                '/payment.v1.PaymentService/GetTransaction',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetTransactionRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_common__pb2.Transaction.FromString,
                _registered_method=True)
        self.GetTransactionByReference = channel.unary_unary(
                '/payment.v1.PaymentService/GetTransactionByReference',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetTransactionByReferenceRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_common__pb2.Transaction.FromString,
                _registered_method=True)
        self.GetTransactionsByInvoice = channel.unary_unary(
                '/payment.v1.PaymentService/GetTransactionsByInvoice',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetTransactionsByInvoiceRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.GetTransactionsByInvoiceResponse.FromString,
                _registered_method=True)
        self.UpdateTransaction = channel.unary_unary(
                '/payment.v1.PaymentService/UpdateTransaction',
                request_serializer=v1_dot_payment_dot_common__pb2.Transaction.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.FindTransactions = channel.unary_unary(
                '/payment.v1.PaymentService/FindTransactions',
                request_serializer=v1_dot_payment_dot_common__pb2.TransactionFilter.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.FindTransactionsResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterProvider(self, request, context):
        """Provider Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProviderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnboardMerchant(self, request, context):
        """Merchant Account Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMerchant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMerchantActiveStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProviderAccountToMerchant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMerchantProviderAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveProviderAccountFromMerchant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMerchantProviderAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMerchantAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInvoiceForPayment(self, request, context):
        """Transaction Processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionByReference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionsByInvoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterProvider,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.RegisterProviderRequest.FromString,
                    response_serializer=v1_dot_payment_dot_common__pb2.Provider.SerializeToString,
            ),
            'GetProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProvider,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetProviderRequest.FromString,
                    response_serializer=v1_dot_payment_dot_common__pb2.Provider.SerializeToString,
            ),
            'ListProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviders,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.ListProvidersRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.ListProvidersResponse.SerializeToString,
            ),
            'UpdateProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProvider,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.UpdateProviderRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateProviderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProviderStatus,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.UpdateProviderStatusRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'OnboardMerchant': grpc.unary_unary_rpc_method_handler(
                    servicer.OnboardMerchant,
                    request_deserializer=v1_dot_payment_dot_common__pb2.MerchantAccount.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateMerchant': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMerchant,
                    request_deserializer=v1_dot_payment_dot_common__pb2.MerchantAccount.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetMerchantActiveStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMerchantActiveStatus,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.SetMerchantActiveStatusRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddProviderAccountToMerchant': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProviderAccountToMerchant,
                    request_deserializer=v1_dot_payment_dot_common__pb2.MerchantProviderAccount.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateMerchantProviderAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMerchantProviderAccount,
                    request_deserializer=v1_dot_payment_dot_common__pb2.MerchantProviderAccount.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveProviderAccountFromMerchant': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveProviderAccountFromMerchant,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.RemoveProviderAccountRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMerchantProviderAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMerchantProviderAccounts,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetMerchantProviderAccountsRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.GetMerchantProviderAccountsResponse.SerializeToString,
            ),
            'GetMerchantAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMerchantAccounts,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetMerchantAccountsRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.GetMerchantAccountsResponse.SerializeToString,
            ),
            'GetInvoiceForPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInvoiceForPayment,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetInvoiceForPaymentRequest.FromString,
                    response_serializer=v1_dot_payment_dot_common__pb2.MerchantInvoicePaymentDetails.SerializeToString,
            ),
            'GetTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransaction,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetTransactionRequest.FromString,
                    response_serializer=v1_dot_payment_dot_common__pb2.Transaction.SerializeToString,
            ),
            'GetTransactionByReference': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionByReference,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetTransactionByReferenceRequest.FromString,
                    response_serializer=v1_dot_payment_dot_common__pb2.Transaction.SerializeToString,
            ),
            'GetTransactionsByInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionsByInvoice,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetTransactionsByInvoiceRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.GetTransactionsByInvoiceResponse.SerializeToString,
            ),
            'UpdateTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTransaction,
                    request_deserializer=v1_dot_payment_dot_common__pb2.Transaction.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'FindTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.FindTransactions,
                    request_deserializer=v1_dot_payment_dot_common__pb2.TransactionFilter.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.FindTransactionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.v1.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.v1.PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/RegisterProvider',
            v1_dot_payment_dot_payment__pb2.RegisterProviderRequest.SerializeToString,
            v1_dot_payment_dot_common__pb2.Provider.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/GetProvider',
            v1_dot_payment_dot_payment__pb2.GetProviderRequest.SerializeToString,
            v1_dot_payment_dot_common__pb2.Provider.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/ListProviders',
            v1_dot_payment_dot_payment__pb2.ListProvidersRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.ListProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/UpdateProvider',
            v1_dot_payment_dot_payment__pb2.UpdateProviderRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProviderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/UpdateProviderStatus',
            v1_dot_payment_dot_payment__pb2.UpdateProviderStatusRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnboardMerchant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/OnboardMerchant',
            v1_dot_payment_dot_common__pb2.MerchantAccount.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMerchant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/UpdateMerchant',
            v1_dot_payment_dot_common__pb2.MerchantAccount.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMerchantActiveStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/SetMerchantActiveStatus',
            v1_dot_payment_dot_payment__pb2.SetMerchantActiveStatusRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddProviderAccountToMerchant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/AddProviderAccountToMerchant',
            v1_dot_payment_dot_common__pb2.MerchantProviderAccount.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMerchantProviderAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/UpdateMerchantProviderAccount',
            v1_dot_payment_dot_common__pb2.MerchantProviderAccount.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveProviderAccountFromMerchant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/RemoveProviderAccountFromMerchant',
            v1_dot_payment_dot_payment__pb2.RemoveProviderAccountRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMerchantProviderAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/GetMerchantProviderAccounts',
            v1_dot_payment_dot_payment__pb2.GetMerchantProviderAccountsRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.GetMerchantProviderAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMerchantAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/GetMerchantAccounts',
            v1_dot_payment_dot_payment__pb2.GetMerchantAccountsRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.GetMerchantAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInvoiceForPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/GetInvoiceForPayment',
            v1_dot_payment_dot_payment__pb2.GetInvoiceForPaymentRequest.SerializeToString,
            v1_dot_payment_dot_common__pb2.MerchantInvoicePaymentDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/GetTransaction',
            v1_dot_payment_dot_payment__pb2.GetTransactionRequest.SerializeToString,
            v1_dot_payment_dot_common__pb2.Transaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionByReference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/GetTransactionByReference',
            v1_dot_payment_dot_payment__pb2.GetTransactionByReferenceRequest.SerializeToString,
            v1_dot_payment_dot_common__pb2.Transaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionsByInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/GetTransactionsByInvoice',
            v1_dot_payment_dot_payment__pb2.GetTransactionsByInvoiceRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.GetTransactionsByInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/UpdateTransaction',
            v1_dot_payment_dot_common__pb2.Transaction.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/FindTransactions',
            v1_dot_payment_dot_common__pb2.TransactionFilter.SerializeToString,
            v1_dot_payment_dot_payment__pb2.FindTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
